#Requires -Version 7.0
<#
.SYNOPSIS
    Shared helpers for the HTTP Security Headers ASVS audit utility scripts.

.DESCRIPTION
    IMMUTABLE — part of the sec-docs skill definition.
    Do NOT edit this file from a project repository (docs/sec-docs/...).

    Exposes:
      New-Finding       — build a finding hashtable (with optional console output)
      Get-SafeArray     — coerce a possibly-null value to an array (never throws)
      Get-SafeBool      — coerce a possibly-null value to [bool] (defaults to $false)
      Invoke-HttpProbe  — HEAD/GET probe returning status code + response headers
      Get-CspDirectives — parse a Content-Security-Policy header into a directive hashtable

    NULL-SAFETY POLICY
        HTTP responses may omit any header. Guard all header lookups with the helpers
        provided here. Never let a missing header throw; emit an appropriate finding instead.
#>

function New-Finding {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Id,
        [Parameter(Mandatory)][string]$Asvs,
        [string]$Owasp = "",
        [Parameter(Mandatory)]
        [ValidateSet("PASS","FAIL","WARN","UNABLE","INFO")]
        [string]$Status,
        [Parameter(Mandatory)][string]$Title,
        [string]$Detail   = "",
        [string]$Evidence = "",
        [string]$AppId    = "",
        [string]$AppEnv   = "",
        [string]$AppUnit  = "",
        [switch]$Quiet
    )
    $finding = @{
        Id       = $Id
        Asvs     = $Asvs
        Owasp    = $Owasp
        Status   = $Status
        Title    = $Title
        Detail   = $Detail
        Evidence = $Evidence
        AppId    = $AppId
        AppEnv   = $AppEnv
        AppUnit  = $AppUnit
    }
    if (-not $Quiet) {
        $color = switch ($Status) {
            "PASS"   { "Green"  }
            "FAIL"   { "Red"    }
            "WARN"   { "Yellow" }
            "UNABLE" { "Cyan"   }
            "INFO"   { "Gray"   }
        }
        $icon = switch ($Status) {
            "PASS"   { "[+]" }
            "FAIL"   { "[!]" }
            "WARN"   { "[~]" }
            "UNABLE" { "[?]" }
            "INFO"   { "[-]" }
        }
        $prefix = if ($AppUnit -and $AppEnv) { "[$AppUnit/$AppEnv] " }
                  elseif ($AppEnv)           { "[$AppEnv] " }
                  else                       { "" }
        Write-Host "$icon [$Asvs] $prefix$Title" -ForegroundColor $color
        if ($Detail) { Write-Host "    $Detail" -ForegroundColor DarkGray }
    }
    return $finding
}

function Get-SafeArray {
    param($Value)
    if ($null -eq $Value) { return ,@() }
    if ($Value -is [string]) { return ,@($Value) }
    if ($Value -is [System.Collections.IEnumerable]) { return ,@($Value) }
    return ,@($Value)
}

function Get-SafeBool {
    param($Value, [bool]$Default = $false)
    if ($null -eq $Value)  { return $Default }
    if ($Value -is [bool]) { return $Value }
    if ($Value -is [string]) {
        $s = $Value.Trim().ToLower()
        if ($s -eq "true"  -or $s -eq "1" -or $s -eq "yes") { return $true  }
        if ($s -eq "false" -or $s -eq "0" -or $s -eq "no"  -or $s -eq "") { return $false }
        return $Default
    }
    if ($Value -is [int] -or $Value -is [long]) { return $Value -ne 0 }
    try { return [bool]$Value } catch { return $Default }
}

function Invoke-HttpProbe {
    <#
    .SYNOPSIS
        Fetches HTTP response headers for a URL using HEAD (fallback: GET).

    .OUTPUTS
        Hashtable: { Success; StatusCode; Headers; FinalUri; Error }
        Headers is a [hashtable] of header-name → joined-value strings (lowercase keys).
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Uri,
        [int]$TimeoutSec          = 15,
        [int]$MaxRedirects        = 10,
        [switch]$NoFollowRedirects,
        [switch]$SkipCertificateCheck
    )

    $result = @{
        Success    = $false
        StatusCode = 0
        Headers    = @{}
        FinalUri   = $Uri
        Error      = ""
    }

    $baseParams = @{
        TimeoutSec         = $TimeoutSec
        SkipHttpErrorCheck = $true
        ErrorAction        = "Stop"
    }
    if ($SkipCertificateCheck) { $baseParams.SkipCertificateCheck = $true }
    $baseParams.MaximumRedirection = if ($NoFollowRedirects) { 0 } else { $MaxRedirects }

    foreach ($method in @("HEAD", "GET")) {
        $params = $baseParams.Clone()
        $params.Uri    = $Uri
        $params.Method = $method
        try {
            $r = Invoke-WebRequest @params
            $result.Success    = $true
            $result.StatusCode = [int]$r.StatusCode
            $hdrs = @{}
            foreach ($kv in $r.Headers.GetEnumerator()) {
                $hdrs[$kv.Key.ToLower()] = ($kv.Value -join ", ")
            }
            $result.Headers  = $hdrs
            $result.FinalUri = $r.BaseResponse?.RequestMessage?.RequestUri?.OriginalString ?? $Uri
            break
        } catch {
            $result.Error = $_.Exception.Message
            if ($method -eq "HEAD") { continue } else { break }
        }
    }
    return $result
}

function Get-CspDirectives {
    <#
    .SYNOPSIS
        Parses a Content-Security-Policy header value into a hashtable of directives.
        Keys are lower-cased directive names; values are the raw directive value strings.
    #>
    param([string]$CspHeader)
    $directives = @{}
    if (-not $CspHeader) { return $directives }
    foreach ($part in ($CspHeader -split ";")) {
        $part = $part.Trim()
        if (-not $part) { continue }
        $tokens = $part -split "\s+", 2
        $name   = $tokens[0].ToLower()
        $value  = if ($tokens.Count -gt 1) { $tokens[1].Trim() } else { "" }
        $directives[$name] = $value
    }
    return $directives
}

Export-ModuleMember -Function `
    New-Finding,
    Get-SafeArray,
    Get-SafeBool,
    Invoke-HttpProbe,
    Get-CspDirectives
