#Requires -Version 7.0
<#
.SYNOPSIS
    Project-specific HTTP Security Headers audit orchestrator. SKILL-MANAGED.

.DESCRIPTION
    AUTO-GENERATED by the sec-docs skill from
    .github/skills/sec-docs/references/headers/Invoke-HttpHeadersAudit.template.ps1.

    EDIT POLICY:
      1. Only the MANIFEST block (between the BEGIN/END markers) is skill-managed.
      2. Everything outside the markers is delegation glue — do not add logic here.
      3. Never hand-edit files in .github/skills/sec-docs/references/headers/.

    OUTPUT (consumed by sec-docs):
      docs/sec-docs/reports/headers/headers-audit-latest.json
      docs/sec-docs/reports/headers/headers-audit-latest.md
#>
[CmdletBinding()]
param(
    [string]$OutputDir = $PSScriptRoot,
    [switch]$SkipCertificateCheck
)

$ErrorActionPreference = "Stop"

# === MANIFEST BEGIN === (skill-managed; do not hand-edit between these markers)

# Deployable units and their base URLs.
# A project may have several units (api, web, integration, ...).
# A unit may have one or more URLs across environments.
# Each entry: @{ Unit; Environment; BaseUrl; DisplayName }
$Endpoints = @(
    # Example (replaced by skill on first generation):
    # @{ Unit = "api"; Environment = "Dev";  BaseUrl = "https://api-dev.example.com";  DisplayName = "api Dev"  }
    # @{ Unit = "web"; Environment = "Prod"; BaseUrl = "https://app.example.com";      DisplayName = "web Prod" }
)

# === MANIFEST END ===

# ─── Locate the skill utility folder
$dir = Get-Item $PSScriptRoot
while ($dir -and -not (Test-Path (Join-Path $dir.FullName ".github"))) {
    $dir = $dir.Parent
}
if (-not $dir) {
    throw "Could not locate the repo root (no .github folder above $PSScriptRoot)."
}
$UtilDir = Join-Path $dir.FullName ".github" "skills" "sec-docs" "references" "headers"

if (-not (Test-Path $UtilDir)) {
    throw "HTTP Headers utility scripts not found at: $UtilDir"
}

if (@($Endpoints).Count -eq 0) {
    Write-Warning "Manifest contains no endpoints. Run /sec-docs to regenerate."
}

Write-Host "=== HTTP Security Headers ASVS Audit ===" -ForegroundColor Cyan
Write-Host "  Endpoints : $(@($Endpoints).Count)"
Write-Host "  Utils     : $UtilDir"
Write-Host "  Output    : $OutputDir"
Write-Host ""

$AllFindings = [System.Collections.Generic.List[hashtable]]::new()

$testScript = Join-Path $UtilDir "Test-HttpSecurityHeaders.ps1"
foreach ($ep in @($Endpoints)) {
    if (-not $ep -or -not $ep.BaseUrl) { continue }
    $label = if ($ep.Unit) { "$($ep.Unit) / $($ep.Environment)" } else { $ep.Environment }
    Write-Host "`n-- Endpoint: $label ($($ep.BaseUrl)) --" -ForegroundColor Cyan
    $epArgs = @{
        BaseUrl     = $ep.BaseUrl
        Environment = if ($ep.Environment) { $ep.Environment } else { "Unknown" }
        Unit        = if ($ep.Unit)        { $ep.Unit }        else { "" }
    }
    if ($SkipCertificateCheck) { $epArgs.SkipCertificateCheck = $true }
    $epOutput = & $testScript @epArgs
    foreach ($f in @($epOutput)) {
        if ($f -is [hashtable]) { [void]$AllFindings.Add($f) }
    }
}

Write-Host "`n-- Writing report --" -ForegroundColor Cyan
$writerScript = Join-Path $UtilDir "Write-HttpHeadersAuditReport.ps1"
& $writerScript `
    -Findings   $AllFindings.ToArray() `
    -Endpoints  $Endpoints `
    -OutputDir  $OutputDir

Write-Host "`nDone." -ForegroundColor Cyan
