#Requires -Version 7.0
<#
.SYNOPSIS
    Shared helpers for the Entra ID ASVS audit utility scripts.

.DESCRIPTION
    IMMUTABLE — part of the sec-docs skill definition.
    Do NOT edit this file from a project repository (docs/sec-docs/...).
    The project-level orchestrator imports this module by relative path.

    Exposes:
      New-Finding         — build a finding hashtable (with optional console output)
      Assert-NoElevatedRoles — abort if the signed-in identity has active write roles
      Get-GraphToken      — obtain a Microsoft Graph token via Azure CLI
      Invoke-Graph        — single Graph REST call (returns parsed object or $null)
      Invoke-GraphOdata   — Graph OData call that returns the .value array
      Get-CodeRoles       — scan repo files for role/permission string literals
      Test-IsGuid         — true if value matches the GUID pattern
      Get-GraphBaseUrl    — base URL for v1.0 Graph endpoint
      Get-SafeArray       — coerce a possibly-null value to an array (never throws)
      Get-SafeBool        — coerce a possibly-null value to [bool] (defaults to $false)

    NULL-SAFETY POLICY
        Graph responses routinely omit properties (e.g. an API-only app has no
        $app.web, a freshly created app has no $app.passwordCredentials, OIDC
        documents may omit grant_types_supported, etc.).
        These helpers and the scripts that use them deliberately do NOT call
        Set-StrictMode so that missing JSON members read as $null instead of
        throwing. Callers must still guard against $null with ?. / ?? / @().
#>

$script:GraphBase        = "https://graph.microsoft.com/v1.0"
$script:GraphToken       = $null
$script:ElevationChecked = $false
$script:GuidPattern      = '[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}'

function Get-GraphBaseUrl { return $script:GraphBase }

function Test-IsGuid {
    param([string]$Value)
    if (-not $Value) { return $false }
    return $Value -match "^$script:GuidPattern$"
}

function Get-SafeArray {
    <#
        Returns an array regardless of input shape. Critical for Graph fields
        that may be $null, a single item, or an array depending on payload.
        Usage: $items = Get-SafeArray $obj.maybeArray
    #>
    param($Value)
    if ($null -eq $Value) { return ,@() }
    if ($Value -is [string]) { return ,@($Value) }
    if ($Value -is [System.Collections.IEnumerable]) { return ,@($Value) }
    return ,@($Value)
}

function Get-SafeBool {
    <#
        Strict bool coercion. PowerShell's native [bool]"false" returns $true
        (any non-empty string is truthy), which silently corrupts audit results
        when Graph returns a stringified boolean. This helper handles common
        string forms explicitly and falls back to $Default on anything weird.
    #>
    param($Value, [bool]$Default = $false)
    if ($null -eq $Value)        { return $Default }
    if ($Value -is [bool])       { return $Value }
    if ($Value -is [string]) {
        $s = $Value.Trim().ToLower()
        if ($s -eq "true"  -or $s -eq "1" -or $s -eq "yes") { return $true  }
        if ($s -eq "false" -or $s -eq "0" -or $s -eq "no" -or $s -eq "") { return $false }
        return $Default
    }
    if ($Value -is [int] -or $Value -is [long]) { return $Value -ne 0 }
    try { return [bool]$Value } catch { return $Default }
}

function New-Finding {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Id,
        [Parameter(Mandatory)][string]$Asvs,
        [string]$Owasp = "",
        [Parameter(Mandatory)]
        [ValidateSet("PASS","FAIL","WARN","UNABLE","INFO")]
        [string]$Status,
        [Parameter(Mandatory)][string]$Title,
        [string]$Detail = "",
        [string]$Evidence = "",
        [string]$AppId = "",
        [string]$AppEnv = "",
        [string]$AppUnit = "",
        [switch]$Quiet
    )
    $finding = @{
        Id       = $Id
        Asvs     = $Asvs
        Owasp    = $Owasp
        Status   = $Status
        Title    = $Title
        Detail   = $Detail
        Evidence = $Evidence
        AppId    = $AppId
        AppEnv   = $AppEnv
        AppUnit  = $AppUnit
    }
    if (-not $Quiet) {
        $color = switch ($Status) {
            "PASS"   { "Green"  }
            "FAIL"   { "Red"    }
            "WARN"   { "Yellow" }
            "UNABLE" { "Cyan"   }
            "INFO"   { "Gray"   }
        }
        $icon = switch ($Status) {
            "PASS"   { "[+]" }
            "FAIL"   { "[!]" }
            "WARN"   { "[~]" }
            "UNABLE" { "[?]" }
            "INFO"   { "[-]" }
        }
        $prefix = if ($AppUnit -and $AppEnv) { "[$AppUnit/$AppEnv] " }
                  elseif ($AppEnv)           { "[$AppEnv] " }
                  else                       { "" }
        Write-Host "$icon [$Asvs] $prefix$Title" -ForegroundColor $color
        if ($Detail) { Write-Host "    $Detail" -ForegroundColor DarkGray }
    }
    return $finding
}

function Assert-NoElevatedRoles {
    <#
    .SYNOPSIS
        Safety gate run once before any token is minted. Verifies the signed-in
        identity has no *active* write-capable role assignment (Owner, Contributor,
        *Administrator, *Write).

    .DESCRIPTION
        Designed for PIM setups where elevated roles are Eligible (inactive) and
        only Reader is permanently active. Eligible-but-unactivated PIM roles do
        NOT appear in `az role assignment list`, so a clean result confirms the
        session is effectively running at Reader scope.

        NOTE: this checks *Azure resource* role assignments (the write surface that
        matters for the resource audit). Entra ID directory roles are a separate
        PIM system; deactivate any elevated directory roles too before auditing.

        If an active write-capable role is found, the function throws to abort the
        read-only audit. Set env var SECDOCS_ALLOW_ELEVATED=1 to downgrade the hard
        stop to a warning (use only when elevated access is intentional).

        Service principals / managed identities (CI) without a resolvable identity
        are skipped with a warning rather than blocked.
    #>
    [CmdletBinding()]
    param()

    if ($script:ElevationChecked) { return }
    $script:ElevationChecked = $true

    $privilegedPatterns = 'Owner', 'Contributor', 'Administrator', 'Write'
    $upn = $null
    $assignments = @()

    try {
        $upn = az ad signed-in-user show --query userPrincipalName -o tsv 2>$null
        if (-not $upn) { $upn = az account show --query user.name -o tsv 2>$null }
        if ($upn) {
            $json = az role assignment list --assignee $upn --all --output json 2>$null
            if ($json) { $assignments = $json | ConvertFrom-Json -ErrorAction Stop }
        }
    } catch {
        Write-Warning "Elevation check could not query role assignments: $($_.Exception.Message)"
        return
    }

    if (-not $upn) {
        Write-Warning "Elevation check skipped: could not determine signed-in identity."
        return
    }

    $elevated = @($assignments | Where-Object {
        $n = $_.roleDefinitionName
        $n -and ($privilegedPatterns | Where-Object { $n -like "*$_*" })
    })

    if ($elevated.Count -eq 0) {
        Write-Host "[+] Elevation check passed for '$upn' — no active write-capable roles (Reader scope)." -ForegroundColor Green
        return
    }

    $list = ($elevated | ForEach-Object { "  - $($_.roleDefinitionName)  @ $($_.scope)" }) -join "`n"
    $msg = "Active elevated role assignment(s) detected for '$upn':`n$list`n`n" +
           "The sec-docs audit is read-only and is meant to run at Reader scope.`n" +
           "If you activated a PIM role (Contributor/Owner/Admin), deactivate it before auditing."

    if ($env:SECDOCS_ALLOW_ELEVATED -eq '1') {
        Write-Warning "$msg`n(SECDOCS_ALLOW_ELEVATED=1 set — proceeding anyway.)"
        return
    }
    throw "$msg`n`nSet SECDOCS_ALLOW_ELEVATED=1 to override this safety check."
}

function Get-GraphToken {
    if ($script:GraphToken) { return $script:GraphToken }
    Assert-NoElevatedRoles
    try {
        $tokenJson = az account get-access-token --resource https://graph.microsoft.com --output json 2>$null
        if ($tokenJson) {
            $parsed = $tokenJson | ConvertFrom-Json -ErrorAction Stop
            if ($parsed -and $parsed.accessToken) {
                $script:GraphToken = $parsed.accessToken
                return $script:GraphToken
            }
        }
    } catch {
        Write-Warning "Failed to obtain Graph token via Azure CLI: $($_.Exception.Message)"
    }
    Write-Warning "Azure CLI not available or not logged in. Run: az login"
    return $null
}

function Invoke-Graph {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Uri,
        [string]$Select = "",
        [switch]$Silent
    )
    $token = Get-GraphToken
    if (-not $token) { return $null }
    $url = if ($Select -and $Uri -notmatch '\?') { "$Uri`?`$select=$Select" }
           elseif ($Select)                      { "$Uri&`$select=$Select" }
           else                                  { $Uri }
    try {
        return Invoke-RestMethod -Uri $url `
            -Headers @{ Authorization = "Bearer $token"; ConsistencyLevel = "eventual" } `
            -Method GET -ErrorAction Stop
    } catch {
        if (-not $Silent) {
            $statusCode = $_.Exception.Response?.StatusCode?.value__
            Write-Warning "Graph call failed [$statusCode]: $url"
        }
        return $null
    }
}

function Invoke-GraphOdata {
    param([string]$Uri, [switch]$Silent)
    $r = Invoke-Graph -Uri $Uri -Silent:$Silent
    if ($null -eq $r) { return @() }
    return Get-SafeArray $r.value
}

function Get-CodeRoles {
    <#
        Scans repo files for likely role/permission string literals.
        Returns an array of unique role names. Never throws on unreadable files.
    #>
    [CmdletBinding()]
    param([Parameter(Mandatory)][string[]]$RepoRoots)

    $roles = [System.Collections.Generic.HashSet[string]]::new()
    foreach ($root in $RepoRoots) {
        if (-not $root -or -not (Test-Path $root)) { continue }
        $files = @()
        try {
            $files = Get-ChildItem -Path $root -Recurse -Include "*.cs","*.ts","*.py" `
                -ErrorAction SilentlyContinue | Where-Object {
                    $_.Name -match '(?i)role|permission|claim' -and
                    $_.FullName -notmatch '[\\/](node_modules|\.git|bin|obj)[\\/]'
                }
        } catch { continue }
        foreach ($file in $files) {
            try {
                Get-Content $file.FullName -ErrorAction SilentlyContinue | ForEach-Object {
                    if ($_ -match '"([A-Z][A-Za-z0-9]{2,39})"') {
                        [void]$roles.Add($Matches[1])
                    }
                }
            } catch { continue }
        }
    }
    return @($roles)
}

Export-ModuleMember -Function `
    New-Finding,
    Assert-NoElevatedRoles,
    Get-GraphToken,
    Invoke-Graph,
    Invoke-GraphOdata,
    Get-CodeRoles,
    Test-IsGuid,
    Get-GraphBaseUrl,
    Get-SafeArray,
    Get-SafeBool
