#Requires -Version 7.0
<#
.SYNOPSIS
    Project-specific TLS audit orchestrator. SKILL-MANAGED.

.DESCRIPTION
    AUTO-GENERATED by the sec-docs skill from
    .github/skills/sec-docs/references/tls/Invoke-TlsAudit.template.ps1.

    EDIT POLICY:
      1. Only the MANIFEST block (between the BEGIN/END markers) is skill-managed.
      2. Everything outside the markers is delegation glue — do not add logic here.
      3. Never hand-edit files in .github/skills/sec-docs/references/tls/.

    OUTPUT (consumed by sec-docs):
      docs/sec-docs/reports/tls/tls-audit-latest.json
      docs/sec-docs/reports/tls/tls-audit-latest.md
#>
[CmdletBinding()]
param(
    [string]$OutputDir = $PSScriptRoot
)

$ErrorActionPreference = "Stop"

# === MANIFEST BEGIN === (skill-managed; do not hand-edit between these markers)

# Deployable units and their TLS endpoints.
# A project may have several units; a unit may have endpoints in multiple environments.
# Port defaults to 443 if omitted in the manifest (orchestrator applies the default below).
# Each entry: @{ Unit; Environment; Hostname; Port; DisplayName }
$Endpoints = @(
    # Example (replaced by skill on first generation):
    # @{ Unit = "api"; Environment = "Dev";  Hostname = "api-dev.example.com";  Port = 443; DisplayName = "api Dev"  }
    # @{ Unit = "web"; Environment = "Prod"; Hostname = "app.example.com";      Port = 443; DisplayName = "web Prod" }
)

# === MANIFEST END ===

# ─── Locate the skill utility folder
$dir = Get-Item $PSScriptRoot
while ($dir -and -not (Test-Path (Join-Path $dir.FullName ".github"))) {
    $dir = $dir.Parent
}
if (-not $dir) {
    throw "Could not locate the repo root (no .github folder above $PSScriptRoot)."
}
$UtilDir = Join-Path $dir.FullName ".github" "skills" "sec-docs" "references" "tls"

if (-not (Test-Path $UtilDir)) {
    throw "TLS utility scripts not found at: $UtilDir"
}

if (@($Endpoints).Count -eq 0) {
    Write-Warning "Manifest contains no endpoints. Run /sec-docs to regenerate."
}

Write-Host "=== TLS ASVS Audit ===" -ForegroundColor Cyan
Write-Host "  Endpoints : $(@($Endpoints).Count)"
Write-Host "  Utils     : $UtilDir"
Write-Host "  Output    : $OutputDir"
Write-Host ""

$AllFindings = [System.Collections.Generic.List[hashtable]]::new()

$testScript = Join-Path $UtilDir "Test-TlsEndpoint.ps1"
foreach ($ep in @($Endpoints)) {
    if (-not $ep -or -not $ep.Hostname) { continue }
    $port  = if ($ep.Port) { [int]$ep.Port } else { 443 }
    $label = if ($ep.Unit) { "$($ep.Unit) / $($ep.Environment)" } else { $ep.Environment }
    Write-Host "`n-- Endpoint: $label ($($ep.Hostname):$port) --" -ForegroundColor Cyan
    $epArgs = @{
        Hostname    = $ep.Hostname
        Port        = $port
        Environment = if ($ep.Environment) { $ep.Environment } else { "Unknown" }
        Unit        = if ($ep.Unit)        { $ep.Unit }        else { "" }
    }
    $epOutput = & $testScript @epArgs
    foreach ($f in @($epOutput)) {
        if ($f -is [hashtable]) { [void]$AllFindings.Add($f) }
    }
}

Write-Host "`n-- Writing report --" -ForegroundColor Cyan
$writerScript = Join-Path $UtilDir "Write-TlsAuditReport.ps1"
& $writerScript `
    -Findings   $AllFindings.ToArray() `
    -Endpoints  $Endpoints `
    -OutputDir  $OutputDir

Write-Host "`nDone." -ForegroundColor Cyan
