#Requires -Version 7.0
<#
.SYNOPSIS
    Shared helpers for the TLS ASVS audit utility scripts.

.DESCRIPTION
    IMMUTABLE — part of the sec-docs skill definition.
    Do NOT edit this file from a project repository (docs/sec-docs/...).

    Exposes:
      New-Finding          — build a finding hashtable (with optional console output)
      Get-SafeArray        — coerce a possibly-null value to an array (never throws)
      Get-SafeBool         — coerce a possibly-null value to [bool] (defaults to $false)
      Invoke-TlsHandshake  — open a TLS connection and collect protocol/cipher/cert details
      Get-CertKeyBits      — extract the public key size in bits from an X509Certificate2

    NULL-SAFETY POLICY
        TLS connection objects may return null for properties that .NET doesn't expose on
        older OS configurations. All accessors use ?. and ?? guards. Never let a missing
        property throw; emit an UNABLE finding instead.
#>

function New-Finding {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Id,
        [Parameter(Mandatory)][string]$Asvs,
        [string]$Owasp = "",
        [Parameter(Mandatory)]
        [ValidateSet("PASS","FAIL","WARN","UNABLE","INFO")]
        [string]$Status,
        [Parameter(Mandatory)][string]$Title,
        [string]$Detail   = "",
        [string]$Evidence = "",
        [string]$AppId    = "",
        [string]$AppEnv   = "",
        [string]$AppUnit  = "",
        [switch]$Quiet
    )
    $finding = @{
        Id       = $Id
        Asvs     = $Asvs
        Owasp    = $Owasp
        Status   = $Status
        Title    = $Title
        Detail   = $Detail
        Evidence = $Evidence
        AppId    = $AppId
        AppEnv   = $AppEnv
        AppUnit  = $AppUnit
    }
    if (-not $Quiet) {
        $color = switch ($Status) {
            "PASS"   { "Green"  }
            "FAIL"   { "Red"    }
            "WARN"   { "Yellow" }
            "UNABLE" { "Cyan"   }
            "INFO"   { "Gray"   }
        }
        $icon = switch ($Status) {
            "PASS"   { "[+]" }
            "FAIL"   { "[!]" }
            "WARN"   { "[~]" }
            "UNABLE" { "[?]" }
            "INFO"   { "[-]" }
        }
        $prefix = if ($AppUnit -and $AppEnv) { "[$AppUnit/$AppEnv] " }
                  elseif ($AppEnv)           { "[$AppEnv] " }
                  else                       { "" }
        Write-Host "$icon [$Asvs] $prefix$Title" -ForegroundColor $color
        if ($Detail) { Write-Host "    $Detail" -ForegroundColor DarkGray }
    }
    return $finding
}

function Get-SafeArray {
    param($Value)
    if ($null -eq $Value) { return ,@() }
    if ($Value -is [string]) { return ,@($Value) }
    if ($Value -is [System.Collections.IEnumerable]) { return ,@($Value) }
    return ,@($Value)
}

function Get-SafeBool {
    param($Value, [bool]$Default = $false)
    if ($null -eq $Value)  { return $Default }
    if ($Value -is [bool]) { return $Value }
    if ($Value -is [string]) {
        $s = $Value.Trim().ToLower()
        if ($s -eq "true"  -or $s -eq "1" -or $s -eq "yes") { return $true  }
        if ($s -eq "false" -or $s -eq "0" -or $s -eq "no"  -or $s -eq "") { return $false }
        return $Default
    }
    if ($Value -is [int] -or $Value -is [long]) { return $Value -ne 0 }
    try { return [bool]$Value } catch { return $Default }
}

function Get-CertKeyBits {
    <#
    .SYNOPSIS
        Returns the public-key bit length of an X509Certificate2.
        Returns 0 if the key size cannot be determined.
    #>
    param([System.Security.Cryptography.X509Certificates.X509Certificate2]$Cert)
    if ($null -eq $Cert) { return 0 }
    try {
        $rsa = $Cert.GetRSAPublicKey()
        if ($rsa) { return $rsa.KeySize }
    } catch {}
    try {
        $ecdsa = $Cert.GetECDsaPublicKey()
        if ($ecdsa) { return $ecdsa.KeySize }
    } catch {}
    try {
        # Fallback: parse from public key info
        return $Cert.PublicKey?.Key?.KeySize ?? 0
    } catch {}
    return 0
}

function Invoke-TlsHandshake {
    <#
    .SYNOPSIS
        Opens a TLS connection to a hostname:port and collects protocol, cipher, and
        certificate details. Never throws — all errors are captured in the result object.

    .OUTPUTS
        Hashtable with fields:
          Success, Hostname, Port, Protocol, CipherAlgorithm, CipherStrength,
          KeyExchangeAlgorithm, NegotiatedSuite,
          CertSubject, CertIssuer, CertThumbprint, CertNotAfter, CertNotBefore,
          CertKeyAlgorithm, CertKeyBits, CertSanNames[],
          IsChainTrusted, SslPolicyErrors, ChainStatusMessages[],
          Error
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Hostname,
        [int]$Port       = 443,
        [int]$TimeoutSec = 20
    )

    $result = @{
        Success              = $false
        Hostname             = $Hostname
        Port                 = $Port
        Protocol             = ""
        CipherAlgorithm      = ""
        CipherStrength       = 0
        KeyExchangeAlgorithm = ""
        NegotiatedSuite      = ""
        CertSubject          = ""
        CertIssuer           = ""
        CertThumbprint       = ""
        CertNotAfter         = $null
        CertNotBefore        = $null
        CertKeyAlgorithm     = ""
        CertKeyBits          = 0
        CertSanNames         = @()
        IsChainTrusted       = $false
        SslPolicyErrors      = ""
        ChainStatusMessages  = @()
        Error                = ""
    }

    $tcpClient = $null
    $sslStream = $null

    try {
        $tcpClient    = [System.Net.Sockets.TcpClient]::new()
        $connectTask  = $tcpClient.ConnectAsync($Hostname, $Port)
        $connected    = $connectTask.Wait([timespan]::FromSeconds($TimeoutSec))

        if (-not $connected) {
            $result.Error = "TCP connection timed out after $TimeoutSec seconds"
            return $result
        }
        if ($connectTask.IsFaulted) {
            $result.Error = ($connectTask.Exception?.InnerExceptions | ForEach-Object { $_.Message }) -join " | "
            return $result
        }

        # Collect SSL policy errors from the validation callback without throwing
        $capturedPolicyErrors  = [System.Net.Security.SslPolicyErrors]::None
        $capturedChainMessages = [System.Collections.Generic.List[string]]::new()

        $certCallback = [System.Net.Security.RemoteCertificateValidationCallback]{
            param($sender, $cert, $chain, $sslPolicyErrors)
            $script:capturedPolicyErrors = $sslPolicyErrors
            foreach ($el in $chain.ChainElements) {
                foreach ($st in $el.ChainElementStatus) {
                    if ($st.Status -ne [System.Security.Cryptography.X509Certificates.X509ChainStatusFlags]::NoError) {
                        $script:capturedChainMessages.Add(
                            "$($el.Certificate.Subject): $($st.Status) — $($st.StatusInformation.Trim())")
                    }
                }
            }
            return $true   # always continue; issues reported as findings
        }

        $stream    = $tcpClient.GetStream()
        $sslStream = [System.Net.Security.SslStream]::new($stream, $false, $certCallback)

        $opts = [System.Net.Security.SslClientAuthenticationOptions]::new()
        $opts.TargetHost          = $Hostname
        $opts.EnabledSslProtocols =
            [System.Security.Authentication.SslProtocols]::Tls12 -bor
            [System.Security.Authentication.SslProtocols]::Tls13

        $authTask = $sslStream.AuthenticateAsClientAsync($opts)
        $authed   = $authTask.Wait([timespan]::FromSeconds($TimeoutSec))

        if (-not $authed) {
            $result.Error = "TLS handshake timed out"
            return $result
        }
        if ($authTask.IsFaulted) {
            $result.Error = ($authTask.Exception?.InnerExceptions | ForEach-Object { $_.Message }) -join " | "
            return $result
        }

        $result.Success              = $true
        $result.Protocol             = $sslStream.SslProtocol.ToString()
        $result.CipherAlgorithm      = $sslStream.CipherAlgorithm.ToString()
        $result.CipherStrength       = $sslStream.CipherStrength
        $result.KeyExchangeAlgorithm = $sslStream.KeyExchangeAlgorithm.ToString()
        $result.SslPolicyErrors      = $capturedPolicyErrors.ToString()
        $result.IsChainTrusted       = ($capturedPolicyErrors -eq [System.Net.Security.SslPolicyErrors]::None)
        $result.ChainStatusMessages  = @($capturedChainMessages)

        # NegotiatedCipherSuite available on .NET 5+
        try   { $result.NegotiatedSuite = $sslStream.NegotiatedCipherSuite.ToString() }
        catch { $result.NegotiatedSuite = "$($sslStream.CipherAlgorithm)_$($sslStream.HashAlgorithm)" }

        # Certificate metadata
        $rawCert = $sslStream.RemoteCertificate
        if ($rawCert) {
            $cert2 = [System.Security.Cryptography.X509Certificates.X509Certificate2]::new($rawCert)
            $result.CertSubject    = $cert2.Subject
            $result.CertIssuer     = $cert2.Issuer
            $result.CertThumbprint = $cert2.Thumbprint
            $result.CertNotAfter   = $cert2.NotAfter
            $result.CertNotBefore  = $cert2.NotBefore
            $result.CertKeyBits    = Get-CertKeyBits $cert2

            try {
                $result.CertKeyAlgorithm = $cert2.PublicKey?.Oid?.FriendlyName ?? "Unknown"
            } catch { $result.CertKeyAlgorithm = "Unknown" }

            # Subject Alternative Names
            try {
                $sanExt = $cert2.Extensions | Where-Object {
                    $_.Oid?.Value -eq "2.5.29.17"  # Subject Alternative Name OID
                }
                if ($sanExt) {
                    $sanText = $sanExt.Format($false)
                    $result.CertSanNames = @(
                        $sanText -split ",\s*" |
                        ForEach-Object { $_ -replace "(?i)^DNS Name=", "" } |
                        Where-Object { $_ -and $_ -notmatch "^IP Address=" }
                    )
                }
            } catch {}
        }
    } catch {
        $result.Error = $_.Exception.Message
    } finally {
        if ($sslStream) { try { $sslStream.Dispose() } catch {} }
        if ($tcpClient) { try { $tcpClient.Dispose() } catch {} }
    }

    return $result
}

Export-ModuleMember -Function `
    New-Finding,
    Get-SafeArray,
    Get-SafeBool,
    Get-CertKeyBits,
    Invoke-TlsHandshake
