#Requires -Version 7.0
<#
.SYNOPSIS
    Project-specific Azure Resource (Key Vault + App Configuration) audit orchestrator.
    SKILL-MANAGED.

.DESCRIPTION
    AUTO-GENERATED by the sec-docs-mini skill from
    .github/skills/sec-docs-mini/references/azure/Invoke-AzureResourceAudit.template.ps1.

    EDIT POLICY:
      1. Only the MANIFEST block (between the BEGIN/END markers) is skill-managed.
      2. Everything outside the markers is delegation glue — do not add logic here.
      3. Never hand-edit files in .github/skills/sec-docs-mini/references/azure/.

    OUTPUT (consumed by sec-docs-mini):
      docs/sec-docs/reports/azure/azure-audit-latest.json
      docs/sec-docs/reports/azure/azure-audit-latest.md

    PREREQUISITES:
      - Azure CLI installed and authenticated: az login
      - The authenticated identity must have Reader on the subscriptions listed, plus
        Key Vault Reader + Keys/List + Secrets/List on each Key Vault.
#>
[CmdletBinding()]
param(
    [string]$OutputDir = $PSScriptRoot
)

$ErrorActionPreference = "Stop"

# === MANIFEST BEGIN === (skill-managed; do not hand-edit between these markers)

# Key Vaults to audit.
# Each entry: @{ Unit; Environment; VaultName; SubscriptionId; ResourceGroup; DisplayName }
$KeyVaults = @(
    # Example (replaced by skill on first generation):
    # @{ Unit = "api";  Environment = "Dev";  VaultName = "kv-cold-wave-dev";  SubscriptionId = "00000000-0000-0000-0000-000000000000"; ResourceGroup = "rg-cold-wave-dev";  DisplayName = "api Dev KV"  }
    # @{ Unit = "api";  Environment = "Prod"; VaultName = "kv-cold-wave-prod"; SubscriptionId = "00000000-0000-0000-0000-000000000000"; ResourceGroup = "rg-cold-wave-prod"; DisplayName = "api Prod KV" }
)

# App Configuration stores to audit.
# Each entry: @{ Unit; Environment; StoreName; SubscriptionId; ResourceGroup; DisplayName }
$AppConfigs = @(
    # Example (replaced by skill on first generation):
    # @{ Unit = "api";  Environment = "Dev";  StoreName = "appcs-cold-wave-dev";  SubscriptionId = "00000000-0000-0000-0000-000000000000"; ResourceGroup = "rg-cold-wave-dev";  DisplayName = "api Dev AppConfig"  }
    # @{ Unit = "api";  Environment = "Prod"; StoreName = "appcs-cold-wave-prod"; SubscriptionId = "00000000-0000-0000-0000-000000000000"; ResourceGroup = "rg-cold-wave-prod"; DisplayName = "api Prod AppConfig" }
)

# === MANIFEST END ===

# ─── Locate the skill utility folder
$dir = Get-Item $PSScriptRoot
while ($dir -and -not (Test-Path (Join-Path $dir.FullName ".github"))) {
    $dir = $dir.Parent
}
if (-not $dir) {
    throw "Could not locate the repo root (no .github folder above $PSScriptRoot)."
}
$UtilDir = Join-Path $dir.FullName ".github" "skills" "sec-docs-mini" "references" "azure"

if (-not (Test-Path $UtilDir)) {
    throw "Azure Resource utility scripts not found at: $UtilDir"
}

$totalResources = @($KeyVaults).Count + @($AppConfigs).Count
if ($totalResources -eq 0) {
    Write-Warning "Manifest contains no Key Vaults or App Configuration stores. Run /sec-docs-mini to regenerate."
}

Write-Host "=== Azure Resource ASVS Audit ===" -ForegroundColor Cyan
Write-Host "  Key Vaults  : $(@($KeyVaults).Count)"
Write-Host "  App Configs : $(@($AppConfigs).Count)"
Write-Host "  Utils       : $UtilDir"
Write-Host "  Output      : $OutputDir"
Write-Host ""

$AllFindings = [System.Collections.Generic.List[hashtable]]::new()

# ─── Key Vault checks
$kvScript = Join-Path $UtilDir "Test-AzureKeyVault.ps1"
foreach ($kv in @($KeyVaults)) {
    if (-not $kv -or -not $kv.VaultName) { continue }
    $label = if ($kv.Unit) { "$($kv.Unit) / $($kv.Environment)" } else { $kv.Environment }
    Write-Host "`n-- Key Vault: $label ($($kv.VaultName)) --" -ForegroundColor Cyan
    $kvArgs = @{
        VaultName      = $kv.VaultName
        SubscriptionId = $kv.SubscriptionId
        ResourceGroup  = $kv.ResourceGroup
        Environment    = if ($kv.Environment) { $kv.Environment } else { "Unknown" }
        Unit           = if ($kv.Unit)        { $kv.Unit }        else { "" }
    }
    $kvOutput = & $kvScript @kvArgs
    foreach ($f in @($kvOutput)) {
        if ($f -is [hashtable]) { [void]$AllFindings.Add($f) }
    }
}

# ─── App Configuration checks
$appScript = Join-Path $UtilDir "Test-AzureAppConfig.ps1"
foreach ($app in @($AppConfigs)) {
    if (-not $app -or -not $app.StoreName) { continue }
    $label = if ($app.Unit) { "$($app.Unit) / $($app.Environment)" } else { $app.Environment }
    Write-Host "`n-- App Config: $label ($($app.StoreName)) --" -ForegroundColor Cyan
    $appArgs = @{
        StoreName      = $app.StoreName
        SubscriptionId = $app.SubscriptionId
        ResourceGroup  = $app.ResourceGroup
        Environment    = if ($app.Environment) { $app.Environment } else { "Unknown" }
        Unit           = if ($app.Unit)        { $app.Unit }        else { "" }
    }
    $appOutput = & $appScript @appArgs
    foreach ($f in @($appOutput)) {
        if ($f -is [hashtable]) { [void]$AllFindings.Add($f) }
    }
}

# ─── Write the report
Write-Host "`n-- Writing report --" -ForegroundColor Cyan
$writerScript = Join-Path $UtilDir "Write-AzureResourceAuditReport.ps1"
& $writerScript `
    -Findings   $AllFindings.ToArray() `
    -KeyVaults  $KeyVaults `
    -AppConfigs $AppConfigs `
    -OutputDir  $OutputDir

Write-Host "`nDone." -ForegroundColor Cyan
