#Requires -Version 7.0
<#
.SYNOPSIS
    Shared helpers for the Azure Resource (Key Vault + App Configuration) ASVS audit scripts.

.DESCRIPTION
    IMMUTABLE — part of the sec-docs skill definition.
    Do NOT edit this file from a project repository (docs/sec-docs/...).

    Exposes:
      New-Finding       — build a finding hashtable (with optional console output)
      Get-SafeArray     — coerce a possibly-null value to an array (never throws)
      Get-SafeBool      — coerce a possibly-null value to [bool] (defaults to $false)
      Get-ArmToken      — obtain an Azure Management token via Azure CLI
      Get-VaultToken    — obtain an Azure Key Vault data-plane token via Azure CLI
      Invoke-Arm        — call the Azure Management REST API (ARM)
      Invoke-DataPlane  — call an Azure data-plane REST API with a given resource URI
      Assert-NoElevatedRoles — abort if the signed-in identity has active write roles

    NULL-SAFETY POLICY
        ARM responses omit properties for resources with default values. Guard all
        property reads with ?. and ?? so missing values never throw.

    AUTH MODEL
        Uses Azure CLI (az account get-access-token) for both management and data-plane
        tokens — consistent with the Entra ID audit scripts. Run `az login` before
        executing the orchestrator.
#>

$script:ArmBase          = "https://management.azure.com"
$script:VaultBase        = "https://vault.azure.net"
$script:ArmToken         = $null
$script:VaultToken       = $null
$script:ElevationChecked = $false

function New-Finding {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Id,
        [Parameter(Mandatory)][string]$Asvs,
        [string]$Owasp = "",
        [Parameter(Mandatory)]
        [ValidateSet("PASS","FAIL","WARN","UNABLE","INFO")]
        [string]$Status,
        [Parameter(Mandatory)][string]$Title,
        [string]$Detail   = "",
        [string]$Evidence = "",
        [string]$AppId    = "",
        [string]$AppEnv   = "",
        [string]$AppUnit  = "",
        [switch]$Quiet
    )
    $finding = @{
        Id       = $Id
        Asvs     = $Asvs
        Owasp    = $Owasp
        Status   = $Status
        Title    = $Title
        Detail   = $Detail
        Evidence = $Evidence
        AppId    = $AppId
        AppEnv   = $AppEnv
        AppUnit  = $AppUnit
    }
    if (-not $Quiet) {
        $color = switch ($Status) {
            "PASS"   { "Green"  }
            "FAIL"   { "Red"    }
            "WARN"   { "Yellow" }
            "UNABLE" { "Cyan"   }
            "INFO"   { "Gray"   }
        }
        $icon = switch ($Status) {
            "PASS"   { "[+]" }
            "FAIL"   { "[!]" }
            "WARN"   { "[~]" }
            "UNABLE" { "[?]" }
            "INFO"   { "[-]" }
        }
        $prefix = if ($AppUnit -and $AppEnv) { "[$AppUnit/$AppEnv] " }
                  elseif ($AppEnv)           { "[$AppEnv] " }
                  else                       { "" }
        Write-Host "$icon [$Asvs] $prefix$Title" -ForegroundColor $color
        if ($Detail) { Write-Host "    $Detail" -ForegroundColor DarkGray }
    }
    return $finding
}

function Get-SafeArray {
    param($Value)
    if ($null -eq $Value) { return ,@() }
    if ($Value -is [string]) { return ,@($Value) }
    if ($Value -is [System.Collections.IEnumerable]) { return ,@($Value) }
    return ,@($Value)
}

function Get-SafeBool {
    param($Value, [bool]$Default = $false)
    if ($null -eq $Value)  { return $Default }
    if ($Value -is [bool]) { return $Value }
    if ($Value -is [string]) {
        $s = $Value.Trim().ToLower()
        if ($s -eq "true"  -or $s -eq "1" -or $s -eq "yes") { return $true  }
        if ($s -eq "false" -or $s -eq "0" -or $s -eq "no"  -or $s -eq "") { return $false }
        return $Default
    }
    if ($Value -is [int] -or $Value -is [long]) { return $Value -ne 0 }
    try { return [bool]$Value } catch { return $Default }
}

function Assert-NoElevatedRoles {
    <#
    .SYNOPSIS
        Safety gate run once before any token is minted. Verifies the signed-in
        identity has no *active* write-capable role assignment (Owner, Contributor,
        *Administrator, *Write).

    .DESCRIPTION
        Designed for PIM setups where elevated roles are Eligible (inactive) and
        only Reader is permanently active. Eligible-but-unactivated PIM roles do
        NOT appear in `az role assignment list`, so a clean result confirms the
        session is effectively running at Reader scope.

        If an active write-capable role is found, the function throws to abort the
        read-only audit. Set env var SECDOCS_ALLOW_ELEVATED=1 to downgrade the hard
        stop to a warning (use only when elevated access is intentional).

        Service principals / managed identities (CI) without a resolvable identity
        are skipped with a warning rather than blocked.
    #>
    [CmdletBinding()]
    param()

    if ($script:ElevationChecked) { return }
    $script:ElevationChecked = $true

    $privilegedPatterns = 'Owner', 'Contributor', 'Administrator', 'Write'
    $upn = $null
    $assignments = @()

    try {
        $upn = az ad signed-in-user show --query userPrincipalName -o tsv 2>$null
        if (-not $upn) { $upn = az account show --query user.name -o tsv 2>$null }
        if ($upn) {
            $json = az role assignment list --assignee $upn --all --output json 2>$null
            if ($json) { $assignments = $json | ConvertFrom-Json -ErrorAction Stop }
        }
    } catch {
        Write-Warning "Elevation check could not query role assignments: $($_.Exception.Message)"
        return
    }

    if (-not $upn) {
        Write-Warning "Elevation check skipped: could not determine signed-in identity."
        return
    }

    $elevated = @($assignments | Where-Object {
        $n = $_.roleDefinitionName
        $n -and ($privilegedPatterns | Where-Object { $n -like "*$_*" })
    })

    if ($elevated.Count -eq 0) {
        Write-Host "[+] Elevation check passed for '$upn' — no active write-capable roles (Reader scope)." -ForegroundColor Green
        return
    }

    $list = ($elevated | ForEach-Object { "  - $($_.roleDefinitionName)  @ $($_.scope)" }) -join "`n"
    $msg = "Active elevated role assignment(s) detected for '$upn':`n$list`n`n" +
           "The sec-docs audit is read-only and is meant to run at Reader scope.`n" +
           "If you activated a PIM role (Contributor/Owner/Admin), deactivate it before auditing."

    if ($env:SECDOCS_ALLOW_ELEVATED -eq '1') {
        Write-Warning "$msg`n(SECDOCS_ALLOW_ELEVATED=1 set — proceeding anyway.)"
        return
    }
    throw "$msg`n`nSet SECDOCS_ALLOW_ELEVATED=1 to override this safety check."
}

function Get-ArmToken {
    if ($script:ArmToken) { return $script:ArmToken }
    Assert-NoElevatedRoles
    try {
        $json = az account get-access-token --resource $script:ArmBase --output json 2>$null
        if ($json) {
            $parsed = $json | ConvertFrom-Json -ErrorAction Stop
            if ($parsed?.accessToken) {
                $script:ArmToken = $parsed.accessToken
                return $script:ArmToken
            }
        }
    } catch {
        Write-Warning "Failed to obtain ARM token via Azure CLI: $($_.Exception.Message)"
    }
    Write-Warning "Azure CLI not available or not logged in for ARM. Run: az login"
    return $null
}

function Get-VaultToken {
    if ($script:VaultToken) { return $script:VaultToken }
    Assert-NoElevatedRoles
    try {
        $json = az account get-access-token --resource $script:VaultBase --output json 2>$null
        if ($json) {
            $parsed = $json | ConvertFrom-Json -ErrorAction Stop
            if ($parsed?.accessToken) {
                $script:VaultToken = $parsed.accessToken
                return $script:VaultToken
            }
        }
    } catch {
        Write-Warning "Failed to obtain Key Vault data-plane token via Azure CLI: $($_.Exception.Message)"
    }
    Write-Warning "Azure CLI not available or not logged in for Key Vault data plane. Run: az login"
    return $null
}

function Invoke-Arm {
    <#
    .SYNOPSIS
        Makes a GET call to the Azure Management REST API.
        Returns the parsed JSON response or $null on failure.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$ResourceId,
        [Parameter(Mandatory)][string]$ApiVersion,
        [switch]$Silent
    )
    $token = Get-ArmToken
    if (-not $token) { return $null }
    $uri = "$($script:ArmBase)$ResourceId`?api-version=$ApiVersion"
    try {
        return Invoke-RestMethod -Uri $uri `
            -Headers @{ Authorization = "Bearer $token" } `
            -Method GET -ErrorAction Stop
    } catch {
        if (-not $Silent) {
            $statusCode = $_.Exception.Response?.StatusCode?.value__
            Write-Warning "ARM call failed [$statusCode]: $uri — $($_.Exception.Message)"
        }
        return $null
    }
}

function Invoke-DataPlane {
    <#
    .SYNOPSIS
        Makes a GET call to an Azure data-plane endpoint (Key Vault, App Config, etc.).
        Returns the parsed JSON response or $null on failure.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Uri,
        [Parameter(Mandatory)][string]$ApiVersion,
        [ValidateSet("vault", "appconfig")]
        [string]$TokenType = "vault",
        [switch]$Silent
    )
    $token = if ($TokenType -eq "vault") { Get-VaultToken } else { Get-ArmToken }
    if (-not $token) { return $null }
    $fullUri = if ($Uri -match "\?") { "$Uri&api-version=$ApiVersion" }
               else { "$Uri`?api-version=$ApiVersion" }
    try {
        return Invoke-RestMethod -Uri $fullUri `
            -Headers @{ Authorization = "Bearer $token" } `
            -Method GET -ErrorAction Stop
    } catch {
        if (-not $Silent) {
            $statusCode = $_.Exception.Response?.StatusCode?.value__
            Write-Warning "Data-plane call failed [$statusCode]: $fullUri — $($_.Exception.Message)"
        }
        return $null
    }
}

Export-ModuleMember -Function `
    New-Finding,
    Get-SafeArray,
    Get-SafeBool,
    Assert-NoElevatedRoles,
    Get-ArmToken,
    Get-VaultToken,
    Invoke-Arm,
    Invoke-DataPlane
