#Requires -Version 7.0
<#
.SYNOPSIS
    Project-specific Entra ID audit orchestrator. SKILL-MANAGED.

.DESCRIPTION
    AUTO-GENERATED by the sec-docs-mini skill from
    .github/skills/sec-docs-mini/references/entraid/Invoke-EntraIDAudit.template.ps1.

    EDIT POLICY (read before changing anything):
      1. Only the MANIFEST block (between the BEGIN/END markers below) is
         skill-managed. The skill rewrites it whenever it detects a new
         environment, deployable unit, or app registration.
      2. Everything OUTSIDE the manifest block is delegation glue. If you
         need a new audit check, add a utility script under
         .github/skills/sec-docs-mini/references/entraid/ and call it from here.
         Do NOT inline new logic into this file.
      3. NEVER hand-edit the files in
         .github/skills/sec-docs-mini/references/entraid/ — they are part of the
         skill definition and changes are reverted by the next skill run.

    OUTPUT (consumed by sec-docs-mini):
      docs/sec-docs/reports/entraid/entraid-audit-latest.json
      docs/sec-docs/reports/entraid/entraid-audit-latest.md
#>
[CmdletBinding()]
param(
    [string]$OutputDir = $PSScriptRoot,
    [switch]$SkipPublicChecks,
    [switch]$SkipConditionalAccess
)

$ErrorActionPreference = "Stop"

# === MANIFEST BEGIN === (skill-managed; do not hand-edit between these markers)

# Tenant GUID. Replaced by the sec-docs-mini skill on first generation.
$TenantId = "{{TENANT_ID}}"

# Deployable units and their app registrations.
# A project may have several units (api1, api2, web, integration, ...).
# A unit may have one or more app registrations across environments.
# Each entry: @{ Unit; Environment; ClientId; DisplayName }
$Applications = @(
    # Example (replaced by skill on first generation):
    # @{ Unit = "api1"; Environment = "Dev";  ClientId = "00000000-0000-0000-0000-000000000000"; DisplayName = "api1 Dev"  }
    # @{ Unit = "api1"; Environment = "Prod"; ClientId = "00000000-0000-0000-0000-000000000000"; DisplayName = "api1 Prod" }
)

# === MANIFEST END ===

# ─── Locate the skill utility folder (.github/skills/sec-docs-mini/references/entraid)
# Walk up from $PSScriptRoot looking for the '.github' marker so this works
# regardless of how deep the orchestrator is nested under the docs repo.
$dir = Get-Item $PSScriptRoot
while ($dir -and -not (Test-Path (Join-Path $dir.FullName ".github"))) {
    $dir = $dir.Parent
}
if (-not $dir) {
    throw "Could not locate the repo root (no .github folder above $PSScriptRoot). " +
          "This orchestrator must live under a checkout of the docs workspace."
}
$RepoRoot = $dir.FullName
$UtilDir  = Join-Path $RepoRoot ".github" "skills" "sec-docs-mini" "references" "entraid"

if (-not (Test-Path $UtilDir)) {
    throw "Entra ID utility scripts not found at: $UtilDir"
}

# ─── Validate manifest before contacting Graph
if ($TenantId -like "*{{*}}*" -or -not $TenantId) {
    throw "TenantId placeholder not replaced. The sec-docs-mini skill should rewrite the manifest block; run /sec-docs-mini."
}
if (@($Applications).Count -eq 0) {
    Write-Warning "Manifest contains no applications. Tenant-level checks will still run."
}

Write-Host "=== Entra ID ASVS Audit ===" -ForegroundColor Cyan
Write-Host "  Tenant   : $TenantId"
Write-Host "  Apps     : $(@($Applications).Count)"
Write-Host "  Utils    : $UtilDir"
Write-Host "  Output   : $OutputDir"
Write-Host ""

$AllFindings = [System.Collections.Generic.List[hashtable]]::new()

# ─── Tenant-level checks (run once)
$scopeClientIds = @($Applications | ForEach-Object { $_.ClientId } | Where-Object { $_ })
$tenantArgs = @{
    TenantId       = $TenantId
    ScopeClientIds = $scopeClientIds
}
if ($SkipPublicChecks)      { $tenantArgs.SkipPublicChecks      = $true }
if ($SkipConditionalAccess) { $tenantArgs.SkipConditionalAccess = $true }

Write-Host "-- Tenant policies --" -ForegroundColor Cyan
$tenantScript  = Join-Path $UtilDir "Test-EntraIDTenantPolicies.ps1"
$tenantOutput  = & $tenantScript @tenantArgs
foreach ($f in @($tenantOutput)) {
    if ($f -is [hashtable]) { [void]$AllFindings.Add($f) }
}

# ─── Per-app checks
$appScript = Join-Path $UtilDir "Test-EntraIDAppRegistration.ps1"
foreach ($app in @($Applications)) {
    if (-not $app -or -not $app.ClientId) { continue }
    $label = if ($app.Unit) { "$($app.Unit) / $($app.Environment)" } else { "$($app.Environment)" }
    Write-Host "`n-- App: $label ($($app.ClientId)) --" -ForegroundColor Cyan
    $appArgs = @{
        ClientId    = $app.ClientId
        TenantId    = $TenantId
        Environment = if ($app.Environment) { $app.Environment } else { "Unknown" }
        Unit        = if ($app.Unit)        { $app.Unit }        else { "" }
        RepoRoots   = @($RepoRoot)
    }
    $appOutput = & $appScript @appArgs
    foreach ($f in @($appOutput)) {
        if ($f -is [hashtable]) { [void]$AllFindings.Add($f) }
    }
}

# ─── Write the report
Write-Host "`n-- Writing report --" -ForegroundColor Cyan
$writerScript = Join-Path $UtilDir "Write-EntraIDAuditReport.ps1"
& $writerScript `
    -Findings     $AllFindings.ToArray() `
    -Applications $Applications `
    -TenantId     $TenantId `
    -OutputDir    $OutputDir `
    -ScannedRoots @($RepoRoot)

Write-Host "`nDone." -ForegroundColor Cyan
